use axum::{
    Router,
    response::{Html, IntoResponse},
    routing::get,
};
use std::net::SocketAddr;

pub async fn serve(
    analysis: String,
    bookmark_count: usize,
) -> Result<(), Box<dyn std::error::Error>> {
    let app = Router::new().route(
        "/",
        get(move || index_handler(analysis.clone(), bookmark_count)),
    );

    let addr = SocketAddr::from(([127, 0, 0, 1], 8080));
    println!("\n🚀 Server running at http://localhost:8080");
    println!("Opening browser...\n");

    // Try to open browser automatically
    let _ = open_browser("http://localhost:8080");

    let listener = tokio::net::TcpListener::bind(addr).await?;
    axum::serve(listener, app).await?;

    Ok(())
}

async fn index_handler(analysis: String, bookmark_count: usize) -> impl IntoResponse {
    let html = format!(
        r#"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bookmark Analysis</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 20px;
        }}
        
        .container {{
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            max-width: 800px;
            width: 100%;
            padding: 40px;
        }}
        
        h1 {{
            color: #667eea;
            margin-bottom: 10px;
            font-size: 2.5em;
        }}
        
        .subtitle {{
            color: #666;
            margin-bottom: 30px;
            font-size: 1.1em;
        }}
        
        .analysis {{
            line-height: 1.8;
            color: #333;
            font-size: 1.1em;
            white-space: pre-wrap;
        }}
        
        .footer {{
            margin-top: 30px;
            padding-top: 20px;
            border-top: 2px solid #eee;
            color: #999;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>🔖 Your Bookmark Analysis</h1>
        <div class="subtitle">Based on {} bookmarks</div>
        <div class="analysis">{}</div>
        <div class="footer">
            Generated by Ollama • Press Ctrl+C to stop the server
        </div>
    </div>
</body>
</html>
        "#,
        bookmark_count, analysis
    );

    Html(html)
}

fn open_browser(url: &str) {
    #[cfg(target_os = "linux")]
    {
        let _ = std::process::Command::new("xdg-open").arg(url).spawn();
    }

    #[cfg(target_os = "macos")]
    {
        let _ = std::process::Command::new("open").arg(url).spawn();
    }

    #[cfg(target_os = "windows")]
    {
        let _ = std::process::Command::new("cmd")
            .args(["/C", "start", url])
            .spawn();
    }
}
